version: "3.8"

services:
  backend:
    image: backend
    ports:
      - 8081:8081
    volumes:
      - ./apps/backend:/usr/src/app/backend
    depends_on:
      - postgres-db
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      BUILD_COMMAND: ${BUILD_COMMAND}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_URL: ${POSTGRES_URL}

  frontend:
    image: frontend
    ports:
      - 5173:5173
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    environment:
      - VITE_BACKEND_BASE_URL=${VITE_BACKEND_BASE_URL}
      - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
      - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
      - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
      - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
      - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
      - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
      - VITE_FIREBASE_MEASUREMENT_ID=${VITE_FIREBASE_MEASUREMENT_ID}

  postgres-db:
    image: postgres:15.3
    ports:
      - 5432:5432
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_URL: ${POSTGRES_URL}
