version: "3.8"

services:
  backend:
    image: backend
    ports:
      - 8081:8081
    volumes:
      - .:/usr/src/app/backend
    depends_on:
      - postgres-db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      BUILD_COMMAND: ${BUILD_COMMAND}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_URL: ${POSTGRES_URL}
  postgres-db:
    image: postgres:15.3
    ports:
      - 5432:5432
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_URL: ${POSTGRES_URL}
