import Head from "next/head";
import { UserDataProvider } from "../contexts/UserData";
import { SessionProvider } from "next-auth/react";
import { NextUIProvider } from "@nextui-org/react";
import { AuthHandler } from "components";
import { Toaster } from "react-hot-toast";
import "styles/global.css";
import "styles/components.css";

export default function App({
  Component,
  pageProps: { session, ...pageProps },
}) {
  return (
    <NextUIProvider>
      <SessionProvider session={session}>
        <UserDataProvider>
          <Head>
            <title>Coders Race</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Toaster position="bottom-right" />
          <AuthHandler auth={Component.auth}>
            <Component {...pageProps} />
          </AuthHandler>
        </UserDataProvider>
      </SessionProvider>
    </NextUIProvider>
  );
}
